scenarios:
  # - rna_pulse_4_substance_specific
  # - rna_pulse_4_substance_independent_rna_protein_module
  - rna_pulse_5_substance_specific
  - rna_pulse_5_substance_independent_rna_protein_module

likelihood_landscapes:
  run: True
  n_grid_points: 100
  n_vector_points: 50
  std_dev: 2.0

