# inspired by: https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/master/workflow/Snakefile

from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.27.0")

##### setup report #####
configfile: "workflow/config.yaml"

##### load rules #####
include: "rules/common.smk"
include: "rules/pymob_infer.smk"
include: "rules/likelihood_landscape.smk"

rule all:
    input:
        get_final_output()