from snakemake.utils import min_version
min_version("8.27")

configfile: "workflow/config.yaml"

module pymob_workflow:
    snakefile:
        # here, it is also possible to provide a plain raw URL like "https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/raw/v2.0.1/workflow/Snakefile"
        github("flo-schu/pymob-workflow", path="workflow/Snakefile", tag="v0.2.5")
    config:
        config

use rule * from pymob_workflow